### ISSUE TITLE
这个app还不支持一维

### ISSUE THREAD

**Issue by KennyLeung** [malxt/WechatQrcode#1]
如题
另，扫描画面一次识别多个二维码，可能适合某种场景，能否做一个一次只识别一个二维码的demo?
![图片](https://user-images.githubusercontent.com/4188953/134472632-c18c5f9c-b2fb-4da4-80b5-68beeda99bf7.png)

**Comment by MALTF** [comment]
新增识别一维码 替换这个依赖就可以了
https://github.com/malxt/opencv/tree/main/opencv

如果需要一次只识别一个二维码
1、可以在编译opencv的源码时修改c++代码；
2、在识别结果里根据需求单独处理；
3、使用zxing或者zbar更方便。

**Comment by impl1874** [comment]
> 新增识别一维码替换这个依赖就可以了 https://github.com/malxt/opencv/tree/main/opencv
> 
> 如果需要一次只识别一个二维码 1、可以在编译opencv的源码时修改c++代码； 2、在识别结果里根据需求单独处理； 3、使用zxing或者zbar更方便。

您好，请问一维支持是lib中opencv动态库提供的吗？

**Comment by impl1874** [comment]
> 新增识别一维码 替换这个依赖就可以了 https://github.com/malxt/opencv/tree/main/opencv
> 
> 如果需要一次只识别一个二维码 1、可以在编译opencv的源码时修改c++代码； 2、在识别结果里根据需求单独处理； 3、使用zxing或者zbar更方便。

您好，编译前的源代码是做过修改吗，我看这是一个新的接口。方便共享一份吗

**Comment by impl1874** [comment]
BarcodeDetector目前支持了三种类型的条码解码，它们分别是EAN13、EAN8、UPC-A
